import { dollarsPerMessage } from "./count.js";
import type { ScanResult } from "./scan.js";

function fmt(n: number): string {
  return n >= 1000 ? `${(n / 1000).toFixed(1)}k` : String(n);
}

function esc(s: string): string {
  return s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]!);
}

export function badgeColor(total: number): string {
  if (total < 5000) return "#3fb950";
  if (total < 20000) return "#d29922";
  if (total < 50000) return "#fb8500";
  return "#f85149";
}

/** A self-contained, shareable HTML budget card. No external assets. */
export function renderHtml(scan: ScanResult): string {
  const max = Math.max(1, ...scan.results.flatMap((r) => r.tools.map((t) => t.tokens)), 1);
  const usd = dollarsPerMessage(scan.total, scan.model);
  const servers = [...scan.results].sort((a, b) => b.totalTokens - a.totalTokens);

  const serverBlocks = servers
    .map((r) => {
      if (r.error) {
        return `<section class="srv"><h2>${esc(r.server)} <span class="err">error: ${esc(r.error)}</span></h2></section>`;
      }
      const sUsd = dollarsPerMessage(r.totalTokens, scan.model);
      const rows = [...r.tools]
        .sort((a, b) => b.tokens - a.tokens)
        .map(
          (t) => `
        <div class="row">
          <div class="name" title="${esc(t.name)}">${esc(t.name)}</div>
          <div class="track"><div class="bar" style="width:${Math.max(2, (t.tokens / max) * 100)}%"></div></div>
          <div class="num">${fmt(t.tokens)}</div>
        </div>`,
        )
        .join("");
      return `
      <section class="srv">
        <h2>${esc(r.server)} <span class="meta">${fmt(r.totalTokens)} tokens · ${r.tools.length} tools${sUsd === null ? "" : ` · ≈ $${sUsd.toFixed(4)}/msg`}</span></h2>
        ${rows}
      </section>`;
    })
    .join("");

  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ctxtax — MCP context budget</title>
<style>
  :root { color-scheme: light dark; }
  body { margin: 0; background: #f6f8fa; color: #1f2328; font: 15px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
  .wrap { max-width: 820px; margin: 32px auto; padding: 0 20px; }
  .card { background: #fff; border: 1px solid #d0d7de; border-radius: 14px; padding: 28px 32px; box-shadow: 0 1px 3px rgba(0,0,0,.06); }
  h1 { margin: 0 0 4px; font-size: 22px; }
  .sub { color: #656d76; margin: 0 0 20px; font-size: 14px; }
  .total { font-size: 34px; font-weight: 700; letter-spacing: -.5px; }
  .total small { font-size: 15px; font-weight: 500; color: #656d76; }
  .est { background: #fff8c5; border: 1px solid #d4a72c55; color: #7d4e00; padding: 8px 12px; border-radius: 8px; font-size: 13px; margin: 14px 0 0; }
  .srv { margin-top: 26px; }
  h2 { font-size: 16px; margin: 0 0 10px; border-bottom: 1px solid #eaeef2; padding-bottom: 6px; }
  h2 .meta { font-weight: 400; color: #656d76; font-size: 13px; }
  .err { color: #cf222e; font-weight: 400; font-size: 13px; }
  .row { display: grid; grid-template-columns: 230px 1fr 56px; align-items: center; gap: 10px; padding: 2px 0; }
  .name { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12.5px; color: #57606a; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .track { background: #eaeef2; border-radius: 4px; height: 12px; }
  .bar { background: #f0b429; height: 12px; border-radius: 4px; }
  .num { font-family: ui-monospace, monospace; font-size: 12.5px; text-align: right; color: #424a53; }
  footer { color: #8c959f; font-size: 12.5px; margin-top: 24px; text-align: center; }
  footer a { color: #8c959f; }
  @media (prefers-color-scheme: dark) {
    body { background: #0d1117; color: #e6edf3; }
    .card { background: #161b22; border-color: #30363d; box-shadow: none; }
    .sub, h2 .meta, .num { color: #8b949e; }
    h2 { border-color: #21262d; } .track { background: #21262d; } .name { color: #8b949e; }
  }
</style>
</head><body>
  <div class="wrap"><div class="card">
    <h1>🧮 MCP context budget</h1>
    <p class="sub">model <code>${esc(scan.model)}</code> · counted with Anthropic count_tokens${scan.mode === "estimate" ? " (estimate)" : ""}</p>
    <div class="total">${fmt(scan.total)} <small>tokens of context tax / request${usd === null ? "" : ` · ≈ $${usd.toFixed(4)}/msg`}</small></div>
    ${scan.mode === "estimate" ? `<p class="est">⚠ Estimate only — set ANTHROPIC_API_KEY for exact counts (free, via Anthropic count_tokens).</p>` : ""}
    ${serverBlocks}
    <footer>Sent on every request that exposes these tools (minus prompt caching). · Generated by <a href="https://github.com/HarryXin0919/ctxtax">ctxtax</a></footer>
  </div></div>
</body></html>
`;
}

/** A flat README badge (self-contained SVG, shields-style). */
export function renderBadgeSvg(total: number): string {
  const label = "context";
  const message = `${fmt(total)} tokens`;
  const color = badgeColor(total);
  const lw = Math.round(label.length * 6.4) + 12;
  const mw = Math.round(message.length * 6.4) + 14;
  const w = lw + mw;
  const lx = (lw / 2) * 10;
  const mx = (lw + mw / 2) * 10;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="20" role="img" aria-label="${label}: ${message}">
<linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient>
<clipPath id="r"><rect width="${w}" height="20" rx="3" fill="#fff"/></clipPath>
<g clip-path="url(#r)">
<rect width="${lw}" height="20" fill="#555"/>
<rect x="${lw}" width="${mw}" height="20" fill="${color}"/>
<rect width="${w}" height="20" fill="url(#s)"/>
</g>
<g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" font-size="110" text-rendering="geometricPrecision">
<text x="${lx}" y="150" transform="scale(.1)" fill="#010101" fill-opacity=".3" textLength="${(lw - 12) * 10}">${label}</text>
<text x="${lx}" y="140" transform="scale(.1)" textLength="${(lw - 12) * 10}">${label}</text>
<text x="${mx}" y="150" transform="scale(.1)" fill="#010101" fill-opacity=".3" textLength="${(mw - 14) * 10}">${message}</text>
<text x="${mx}" y="140" transform="scale(.1)" textLength="${(mw - 14) * 10}">${message}</text>
</g>
</svg>
`;
}

/** A shields.io endpoint-badge JSON (host it, then reference via img.shields.io/endpoint?url=...). */
export function renderBadgeJson(total: number): string {
  return JSON.stringify(
    { schemaVersion: 1, label: "context", message: `${fmt(total)} tokens`, color: badgeColor(total) },
    null,
    2,
  );
}
